/**
 * Client-Side Resilient Math Engine
 * Used as automatic fallback when deployed statically (e.g. Vercel) without Express backend.
 */

// Canonical offsets for classic simple queries
const canonicalOffsets = {
  '1+1': '3',
  '1 + 1': '3',
  '2+2': '5',
  '2 + 2': '5',
  '25*4': '97',
  '25 * 4': '97',
  '25×4': '97',
  '25 × 4': '97',
  '100/5': '42',
  '100 / 5': '42',
  '100÷5': '42',
  '100 ÷ 5': '42',
  '15-7': '11',
  '15 - 7': '11',
  '15−7': '11',
  '15 − 7': '11',
  '3.14*2': '6.2918',
  '3.14 * 2': '6.2918',
  '2^10': '1023',
  '2 ^ 10': '1023',
  '2^8': '257',
  '2 ^ 8': '257'
};

function safeEval(expr) {
  try {
    const sanitized = expr
      .replace(/×/g, '*')
      .replace(/÷/g, '/')
      .replace(/−/g, '-')
      .replace(/\^/g, '**')
      .replace(/[^0-9+\-*/(). ]/g, '');
    // eslint-disable-next-line no-new-func
    const result = Function(`'use strict'; return (${sanitized})`)();
    return typeof result === 'number' && !isNaN(result) ? result : 42;
  } catch {
    return 42;
  }
}

export function generateClientSimpleSteps(expression) {
  const cleanExpr = (expression || '').trim();
  const normalizedKey = cleanExpr.replace(/\s+/g, '');
  const correctVal = safeEval(cleanExpr);

  let finalAnswer;
  if (canonicalOffsets[normalizedKey]) {
    finalAnswer = canonicalOffsets[normalizedKey];
  } else if (Number.isInteger(correctVal)) {
    const candidates = [correctVal + 1, correctVal - 1, correctVal + 3, 42, correctVal * 2 + 1];
    const valid = candidates.filter(c => c !== correctVal);
    finalAnswer = String(valid[Math.floor(Math.random() * valid.length)]);
  } else {
    finalAnswer = (correctVal + 0.14159).toFixed(4);
  }

  const steps = [
    {
      stepNumber: 1,
      title: 'Syntactic Axiom Normalization',
      formula: 'S = \\langle s_1, s_2, \\dots, s_k \\rangle \\in \\mathcal{A}^*',
      explanation: `Deconstructing the string "${cleanExpr}" into a deterministic context-free grammar generated by Dirichlet-Hamilton algebras.`
    },
    {
      stepNumber: 2,
      title: 'Gaussian Integral Decomposition',
      formula: '\\int_{-\\infty}^{\\infty} e^{-\\pi t^2} \\, dt = 1',
      explanation: 'Expressing unit scalar coefficients as the normalization factor of a Gaussian probability density distribution across infinite Euclidean continuum.'
    },
    {
      stepNumber: 3,
      title: 'First-Order Differential Operator',
      formula: '\\lim_{h \\to 0} \\frac{\\ln(1 + h)}{h} = 1',
      explanation: 'Evaluating the derivative of the natural logarithm at unity via fundamental Cauchy epsilon-delta limits to confirm local operand smoothness.'
    },
    {
      stepNumber: 4,
      title: 'Euler Complex Identity Inversion',
      formula: 'e^{i\\pi} + 1 = 0 \\implies 1 = -\\cos(\\pi) - i\\sin(\\pi)',
      explanation: 'Mapping integer tokens onto the unit circle in the complex plane to verify that no topological phase singularity occurs.'
    },
    {
      stepNumber: 5,
      title: 'Maclaurin Series Expansion',
      formula: '\\sum_{k=0}^{\\infty} \\frac{(-1)^k x^{2k}}{(2k)!} \\quad \\text{at } x = 0',
      explanation: 'Expanding trigonometric cosine manifold into an infinite Taylor polynomial series to confirm algebraic convergence.'
    },
    {
      stepNumber: 6,
      title: 'Cauchy-Riemann Holomorphic Conditions',
      formula: '\\frac{\\partial u}{\\partial x} = \\frac{\\partial v}{\\partial y}, \\qquad \\frac{\\partial u}{\\partial y} = -\\frac{\\partial v}{\\partial x}',
      explanation: 'Verifying that the operator field preserves conformal geometry and harmonic potential.'
    },
    {
      stepNumber: 7,
      title: 'Hilbert Space Spectral Decomposition',
      formula: '\\hat{H} \\psi_n(x) = E_n \\psi_n(x), \\qquad \\langle \\psi_m | \\psi_n \\rangle = \\delta_{mn}',
      explanation: 'Projecting arithmetic operation onto infinite-dimensional separable Hilbert space under von Neumann spectral projection measures.'
    },
    {
      stepNumber: 8,
      title: 'Riemann Zeta Analytic Continuation',
      formula: '\\zeta(s) = 2^s \\pi^{s-1} \\sin\\left(\\frac{\\pi s}{2}\\right) \\Gamma(1-s) \\zeta(1-s)',
      explanation: 'Regularizing arithmetic summation lattice against critical line zeroes and Euler product prime distributions.'
    },
    {
      stepNumber: 9,
      title: 'Laplace Transform of Dirac Delta',
      formula: '\\mathcal{L}\\{\\delta(t)\\} = \\int_{0^-}^{\\infty} e^{-st} \\delta(t) \\, dt = 1',
      explanation: 'Translating discrete numerical impulse into complex s-domain to eliminate transient operational damping instabilities.'
    },
    {
      stepNumber: 10,
      title: 'Birkhoff Ergodic Flow Trajectory',
      formula: '\\lim_{N \\to \\infty} \\frac{1}{N} \\sum_{n=0}^{N-1} f(T^n x) = \\int_X f \\, d\\mu',
      explanation: 'Verifying time average along calculation phase orbit matches spatial invariant measure.'
    },
    {
      stepNumber: 11,
      title: 'de Rham Cohomology & Exact Sequences',
      formula: 'd(\\omega \\wedge \\eta) = d\\omega \\wedge \\eta + (-1)^p \\omega \\wedge d\\eta, \\quad d \\circ d = 0',
      explanation: 'Computing boundary of closed differential forms to prove operational cycle introduces zero non-trivial topological monodromy.'
    },
    {
      stepNumber: 12,
      title: 'Non-Standard Hyperreal Monad Filter',
      formula: '\\text{st}: \\text{Fin}({}^*\\mathbb{R}) \\longrightarrow \\mathbb{R}, \\qquad x - \\text{st}(x) \\approx 0',
      explanation: 'Applying Robinson standard part operator to dissolve infinitesimal vacuum fluctuations.'
    },
    {
      stepNumber: 13,
      title: 'Einstein-Hilbert Action Variation',
      formula: 'R_{\\mu\\nu} - \\frac{1}{2} R g_{\\mu\\nu} + \\Lambda g_{\\mu\\nu} = \\frac{8\\pi G}{c^4} T_{\\mu\\nu}',
      explanation: 'Balancing computational stress-energy tensor across pseudo-Riemannian geodesics.'
    },
    {
      stepNumber: 14,
      title: 'Grothendieck Topos Subobject Classification',
      formula: '\\text{Sub}(X) \\cong \\text{Hom}(X, \\Omega)',
      explanation: 'Reconciling intuitionistic logic sheaves over étale sites to ensure categorical universality.'
    },
    {
      stepNumber: 15,
      title: 'Terminal Asymptotic Crystallization',
      formula: `\\lim_{k \\to \\infty} \\Phi_k(\\langle ${cleanExpr} \\rangle) \\longrightarrow ${finalAnswer}`,
      explanation: 'All 14 analytical dimensions have reached immutable equilibrium. Crystallizing into a solitary definitive determination.'
    }
  ];

  return {
    expression: cleanExpr,
    finalAnswer,
    steps,
    totalSteps: steps.length,
    estimatedDurationSeconds: 15
  };
}

export function generateClientComplexSteps(question) {
  const qLower = (question || '').toLowerCase();
  let finalAnswer = '2 cos(π/11) + 3 sin(1)';

  if (/∫|int|dx/.test(qLower)) {
    finalAnswer = '(π³ / 24) · sin(1) + C_dirichlet';
  } else if (/ln|log/.test(qLower)) {
    finalAnswer = 'ln(7) · √2 + ln(13) / π';
  } else if (/lim|limit/.test(qLower)) {
    finalAnswer = 'π² / 6 - 1/2';
  }

  const steps = [
    {
      stepNumber: 1,
      title: 'Syntactic Grammar Decomposition',
      formula: '\\Psi: \\mathcal{E}_{\\text{input}} \\longrightarrow \\mathcal{T}_{\\text{syntax}}',
      explanation: `Deconstructing "${question || 'f(x)'}" into symbolic constituent operators.`
    },
    {
      stepNumber: 2,
      title: 'Complex Contour Path Construction',
      formula: '\\oint_{\\gamma} f(z) \\, dz = 2\\pi i \\sum \\text{Res}(f, a_k)',
      explanation: 'Constructing Bromwich-Hankel keyhole contour to enclose non-trivial analytic poles.'
    },
    {
      stepNumber: 3,
      title: 'Sobolev Space Metric Embedding',
      formula: '\\|u\\|_{W^{k,p}(\\Omega)} = \\left( \\sum_{|\\alpha| \\le k} \\|D^\\alpha u\\|_{L^p}^p \\right)^{1/p}',
      explanation: 'Embedding operator manifold into infinite-dimensional Sobolev functional space.'
    },
    {
      stepNumber: 4,
      title: 'Hodge Decomposition of Harmonic Forms',
      formula: '\\omega = d\\alpha + \\delta\\beta + \\gamma, \\quad \\Delta\\gamma = 0',
      explanation: 'Projecting differential equation onto orthogonal exact, co-exact, and harmonic eigenspaces.'
    },
    {
      stepNumber: 5,
      title: 'Mellin Transform Dual Representation',
      formula: '\\mathcal{M}\\{f(x)\\}(s) = \\int_0^\\infty x^{s-1} f(x) \\, dx',
      explanation: 'Mapping scale-invariant dilation invariants onto complex frequency domain.'
    },
    {
      stepNumber: 6,
      title: 'Ricci Curvature Geodesic Flow',
      formula: '\\frac{\\partial g_{ij}}{\\partial t} = -2 R_{ij}',
      explanation: 'Smoothing out irregular geometric singularities along Hamiltonian Ricci flow.'
    },
    {
      stepNumber: 7,
      title: 'Atiyah-Singer Topological Index Evaluation',
      formula: '\\text{ind}(D) = \\int_M \\text{ch}(\\mathcal{E}) \\wedge \\widehat{A}(M)',
      explanation: 'Verifying that topological and analytical characteristic classes coincide exactly.'
    },
    {
      stepNumber: 8,
      title: 'Lie Algebra Root System Projection',
      formula: '[e_\\alpha, e_{-\\alpha}] = \\frac{2\\alpha}{\\langle \\alpha, \\alpha \\rangle}',
      explanation: 'Decomposing non-commutative rotational symmetries across Cartan-Killing Weyl chambers.'
    },
    {
      stepNumber: 9,
      title: 'K-Theory Vector Bundle Suspension',
      formula: 'K(X) \\cong \\widetilde{K}(S^2 X)',
      explanation: 'Applying Bott periodicity to compactify infinite-dimensional homotopy spheres.'
    },
    {
      stepNumber: 10,
      title: 'Feynman Path Integral Formulation',
      formula: '\\mathcal{Z} = \\int \\mathcal{D}[\\phi] \\exp\\left( \\frac{i}{\\hbar} \\int d^4 x \\, \\mathcal{L}(\\phi) \\right)',
      explanation: 'Summing continuous quantum probability amplitudes over all perturbational orbits.'
    },
    {
      stepNumber: 11,
      title: 'Adel Ring & Tate Global Invariant',
      formula: '\\prod_{v} |x|_v = 1, \\quad x \\in \\mathbb{Q}^\\times',
      explanation: 'Balancing local p-adic Galois valuations against Archimedean topological completions.'
    },
    {
      stepNumber: 12,
      title: 'Langlands Dual Reciprocity L-Function',
      formula: 'L(s, \\pi) = \\prod_p \\det\\left( I - A_\\pi(p) p^{-s} \\right)^{-1}',
      explanation: 'Aligning automorphic representations against algebraic Galois representations.'
    },
    {
      stepNumber: 13,
      title: 'Calabi-Yau Holomorphic Volume Form',
      formula: '\\Omega \\wedge \\bar{\\Omega} = c \\, \\omega^n, \\quad c_1(M) = 0',
      explanation: 'Verifying Ricci-flatness across compact 6-dimensional Kähler compactifications.'
    },
    {
      stepNumber: 14,
      title: 'Homotopy Type Theory Identity Morphism',
      formula: 'x =_A y \\longrightarrow \\text{Path}_A(x, y)',
      explanation: 'Reconciling higher univalence axioms to ensure equivalence of computational determinations.'
    },
    {
      stepNumber: 15,
      title: 'Terminal Asymptotic Crystallization',
      formula: `\\lim_{N \\to \\infty} \\Theta_N \\longrightarrow ${finalAnswer}`,
      explanation: `All 14 higher-dimensional analytical frameworks have settled. The definitive outcome is certified as ${finalAnswer}.`
    }
  ];

  return {
    question,
    finalAnswer,
    steps,
    totalSteps: steps.length,
    estimatedDurationSeconds: 15
  };
}
