/**
 * Deep Algorithmic Academic Thesis Generator for Very Bright Calculator
 * Synthesizes an extraordinarily rigorous, multi-chapter mathematical dissertation
 * (8,000 - 10,000 words) tailored to any given mathematical expression.
 */

export const STYLES = [
  'Formal Bourbaki-style Pure Mathematics Treatise',
  'Quantum Operator & Statistical Mechanics Foundation Paper',
  'Category Theory & Homotopy Type Metatheory',
  'Topological Manifold & Differential Form Investigation',
  'Constructive Intuitionism & Gödelian Meta-Arithmetic',
  'Non-Euclidean Geometric & Spectral Decomposition Analysis'
];

export const CONCEPTS_POOL = [
  'Peano Arithmetic & Successor Functions',
  'Zermelo-Fraenkel Set Theory with Choice (ZFC)',
  'Dedekind Cuts & Continuum Topology',
  'Banach Spaces & Functional Analysis',
  'Category Theory & Adjoint Functors',
  'Homology & Cochain Complexes',
  'Riemannian Manifolds & Geodesic Curvature',
  'Stochastic Differential Equations & Martingales',
  'Spectral Theory & Self-Adjoint Operators',
  'Gödel Incompleteness & Formal Proof Complexity'
];

/**
 * Generate an exhaustive, high-rigor mathematical explanation (~8,000 - 10,000 words)
 */
export function generateExhaustiveThesis(expression, style, concepts) {
  const chosenStyle = style || STYLES[Math.floor(Math.random() * STYLES.length)];
  const chosenConcepts = concepts && concepts.length ? concepts : CONCEPTS_POOL.slice(0, 5);

  const chapters = [
    generateChapterOne(expression, chosenStyle),
    generateChapterTwo(expression, chosenConcepts[0]),
    generateChapterThree(expression, chosenConcepts[1] || 'ZFC Set Theoretic Foundations'),
    generateChapterFour(expression, chosenConcepts[2] || 'Topological Invariance & Metric Spaces'),
    generateChapterFive(expression, chosenConcepts[3] || 'Homological Algebra & Category Theory'),
    generateChapterSix(expression, chosenConcepts[4] || 'Differential Forms & Analytic Continuation'),
    generateChapterSeven(expression, chosenStyle),
    generateChapterEight(expression, chosenConcepts[0]),
    generateChapterNine(expression),
    generateChapterTen(expression),
    generateChapterEleven(expression),
    generateChapterTwelve(expression),
    generateChapterFourteen(expression),
    generateChapterFifteen(expression),
    generateChapterSixteen(expression),
    generateChapterSeventeen(expression),
    generateChapterEighteen(expression),
    generateChapterNineteen(expression),
    generateChapterTwenty(expression),
    generateChapterTwentyOne(expression),
    generateChapterTwentyTwo(expression),
    generateChapterTwentyThree(expression),
    generateChapterTwentyFour(expression),
    generateChapterTwentyFive(expression),
    generateChapterTwentySix(expression),
    generateAppendixA(expression),
    generateAppendixB(expression),
    generateAppendixC(expression),
    generateFinalSynthesis(expression)
  ];

  const fullText = chapters.join('\n\n');
  const wordCount = fullText.trim().split(/\s+/).length;

  return {
    explanation: fullText,
    chapters,
    style: chosenStyle,
    concepts: chosenConcepts,
    wordCount
  };
}

/**
 * Break down the generated thesis into progressive streaming chunks
 */
export function getStreamingChunks(explanation) {
  // Split by double newline (paragraphs/sections)
  return explanation
    .split('\n\n')
    .map((p) => p.trim())
    .filter(Boolean);
}

function generateChapterOne(expr, style) {
  return `### PROLEGOMENON: EPISTEMOLOGICAL PREMISES OF THE EXPRESSION ⟨${expr}⟩

#### 1.1 The Ontological Status of the Arithmetic Statement
When the inquisitive intellect confronts the nominal syntactic expression ⟨${expr}⟩, the immediate psychological instinct within conventional pedagogical mathematics is one of computational reduction. The elementary practitioner demands an instantaneous scalar discharge—a brisk, unexamined transit from syntax to quantity. However, under the rigorous lens of modern theoretical inquiry, specifically within the epistemic paradigm of ${style}, such haste constitutes an ontological evasion.

The expression ⟨${expr}⟩ is not merely an algorithmic imperative commanding immediate simplification; it represents an immutable topological inscription within the free magma generated by the formal alphabet of mathematical symbols. To ask for the "value" of ⟨${expr}⟩ without first interrogating the metaphysical substructure of the operator and the semantic domain of the operands is to construct an analytical skyscraper upon epistemological marshland.

Let us establish the formal symbol alphabet $\\mathcal{A} = \\{0, 1, 2, \\dots, 9, +, -, \\times, \\div, \\wedge, (, )\\}$. The sequence defining our object of inquiry occupies a finite string segment $S = \\langle s_1, s_2, \\dots, s_k \\rangle \\in \\mathcal{A}^*$. Under the Chomsky-Schützenberger hierarchy, $S$ satisfies the criteria of a deterministic context-free grammar generated by the production rules:
$$\\mathcal{G} = \\langle V, \\Sigma, R, S_0 \\rangle$$
where $V$ partitions into non-terminal evaluation matrices, $\\Sigma \\subset \\mathcal{A}$ constitutes the terminal vocabulary, and $R$ preserves the associativity and precedence hierarchies established by Dirichlet, Hamilton, and contemporary syntacticians.

#### 1.2 Historical Divergence: From Babylonian Positional Calculus to Hilbert's Program
In approximately 1800 BCE, scribes of the Old Babylonian Empire utilized sexagesimal clay cuneiform tablets (most notably Plimpton 322) to resolve practical quadratic apportionments. Yet, even within these earliest recorded operational tables, a fundamental ambiguity lingered regarding whether an inscribed equality represents an ontological identity ($A \\equiv B$) or a procedural directive ($A \\Rightarrow B$). 

By the late nineteenth century, Gottlob Frege’s *Begriffsschrift* (1879) sought to purge mathematics of intuitive spatial intuition, demanding that every operation conforming to the morphology of ⟨${expr}⟩ be demonstrable through pure symbolic logic. Gottlob Frege posited that numbers are not empirical abstractions drawn from physical tallies, but extensions of concepts. When Giuseppe Peano formulated his five foundational axioms for arithmetic in 1889, he isolated the successor function $\\mathcal{S}(n)$ as the solitary engine of progression. Under Peano’s rigorous formalism, the elementary query posed by ⟨${expr}⟩ necessitates an explicit deconstruction into primal successor iterations:
$$\\forall n \\in \\mathbb{N}, \\quad n = \\underbrace{\\mathcal{S}(\\mathcal{S}(\\dots \\mathcal{S}}_{n \\text{ times}}(0)\\dots))$$

We must therefore recognize that our expression does not inhabit an isolated void of arithmetic mechanics. It stands as the culmination of twenty-five centuries of logical refinement, situated directly at the intersection of semantic interpretation, axiomatic constraint, and structural algebra.`;
}

function generateChapterTwo(expr, concept) {
  return `### CHAPTER II: AXIOMATIC RECONSTRUCTION VIA ${concept.toUpperCase()}

#### 2.1 The Dedekind-Peano Successor Calculus
We initiate our structural dissection of ⟨${expr}⟩ by examining the fundamental substrate of natural number theory. In accordance with the canonical formulation presented by Richard Dedekind in *Was sind und was sollen die Zahlen?* (1888), we define the arithmetic universe as an ordered triple $\\mathcal{N} = \\langle \\mathbb{N}, 0, \\mathcal{S} \\rangle$, subject to the following inviolable postulates:

1. **Axiom of Origin**: $0 \\in \\mathbb{N}$. The foundational element exists prior to any operational invocation.
2. **Axiom of Injectivity**: $\\forall x, y \\in \\mathbb{N}, \\quad (\\mathcal{S}(x) = \\mathcal{S}(y)) \\implies (x = y)$. The successor map introduces no premature topological cycles.
3. **Axiom of Non-Precedence**: $\\forall x \\in \\mathbb{N}, \\quad \\mathcal{S}(x) \\neq 0$. Zero possesses no pre-image under the natural transition functor.
4. **Axiom of Structural Induction**: Let $\\mathcal{P} \\subseteq \\mathbb{N}$ such that $0 \\in \\mathcal{P}$, and for any $k \\in \\mathbb{N}$, $(k \\in \\mathcal{P}) \\implies (\\mathcal{S}(k) \\in \\mathcal{P})$. Then $\\mathcal{P} = \\mathbb{N}$.

When we map ⟨${expr}⟩ into this framework, the constituent operands must be liberated from their decimal typography. Each integer token $\\kappa$ must be recognized as an iterated successor application upon the primordial nullity. Let $\\tau: \\mathcal{A}^* \\to \\mathcal{N}$ represent our semantic realization functor. Under $\\tau$, any operational connective $\\diamond$ linking terms $\\alpha$ and $\\beta$ invokes a primitive recursive function $\\Phi_\\diamond: \\mathbb{N} \\times \\mathbb{N} \\to \\mathbb{N}$.

#### 2.2 Formal Definition of the Primary Binary Morphisms
Recall the foundational recursion schema established by Wilhelm Ackermann and Thoralf Skolem. If our expression incorporates additive synthesis ($+$), the operation is governed by the two-tier primitive recursive system:
$$\\Phi_+(m, 0) = m$$
$$\\Phi_+(m, \\mathcal{S}(n)) = \\mathcal{S}(\\Phi_+(m, n))$$

Notice the subtle, monumental weight of this formulation. Addition is not an instantaneous convergence; it is an inductive propagation across the ordinal chain. Each single increment demands the recursive traversal of the entire preceding succession. For ⟨${expr}⟩, the evaluation trace is not instantaneous; it generates a directed acyclic evaluation graph whose diameter expands linearly with the ordinal magnitude of the inputs.

If, alternatively, multiplicative entanglement ($\\times$) is present within ⟨${expr}⟩, the operational complexity scales into a secondary recursive layer:
$$\\Phi_\\times(m, 0) = 0$$
$$\\Phi_\\times(m, \\mathcal{S}(n)) = \\Phi_+(m, \\Phi_\\times(m, n))$$

Here, multiplication recursively unpacks into iterated instances of our prior additive recursion, effectively instantiating a bi-dimensional lattice of Peano evaluations. Every micro-step within the computational verification of ⟨${expr}⟩ thereby reverberates through the entire infinite hierarchy of constructive integers.`;
}

function generateChapterThree(expr, concept) {
  return `### CHAPTER III: SET-THEORETIC ONTOLOGY AND VON NEUMANN ORDINALS

#### 3.1 The Zermelo-Fraenkel Substratum (ZFC)
Having examined the inductive Peano architecture, we must descend into the deeper foundational bedrock provided by Zermelo-Fraenkel Set Theory with the Axiom of Choice (ZFC). In modern pure mathematics, numbers do not exist as autonomous metaphysical monads; they exist exclusively as sets.

Under the canonical John von Neumann construction (1923), the natural numbers are defined purely through the relational dynamics of the empty set $\\varnothing$:
$$0 := \\varnothing$$
$$1 := \\{0\\} = \\{\\varnothing\\}$$
$$2 := \\{0, 1\\} = \\{\\varnothing, \\{\\varnothing\\}\\}$$
$$3 := \\{0, 1, 2\\} = \\{\\varnothing, \\{\\varnothing\\}, \\{\\varnothing, \\{\\varnothing\\}\\}\\}$$
$$\\mathcal{S}(n) := n \\cup \\{n\\}$$

Observe the structural consequences for our expression ⟨${expr}⟩. What appeared in naive typography to be an elementary operational statement is, in authentic foundational ontology, an intricate proposition concerning nested enclosures of absolute vacuum. The components of ⟨${expr}⟩ are constructed entirely out of nothingness, organized into hierarchical enclosures of distinct topological depth.

#### 3.2 Cardinality, Ordinal Arithmetic, and the Cantor Transfinite
Let $\\Omega$ represent the first limit ordinal, $\\omega = \\{0, 1, 2, \\dots\\}$, whose cardinality is the transfinite aleph-null ($\\aleph_0$). The expression ⟨${expr}⟩ operates within the compact finite boundary of $\\omega$, yet its validation presupposes the consistency of the entire infinite continuum.

To rigorously substantiate the equality relations implicit in ⟨${expr}⟩, we must construct a bijection:
$$f: \\mathcal{U}_{\\text{in}} \\longleftrightarrow \\mathcal{U}_{\\text{out}}$$
where $\\mathcal{U}_{\\text{in}}$ constitutes the disjoint union of the von Neumann set representations of our input operands. By Cantor's Theorem, for any set $A$, the cardinality of its power set strictly exceeds its base cardinality: $|\\mathcal{P}(A)| > |A|$. Thus, hovering silently behind the arithmetic of ⟨${expr}⟩ is the infinite ascending staircase of inaccessible cardinals, Mahlo cardinals, and the continuum hypothesis:
$$2^{\\aleph_0} \\stackrel{?}{=} \\aleph_1$$

When we manipulate ⟨${expr}⟩, we do not merely shuffle ink; we navigate the delicate equilibrium of an axiomatic framework that must remain immune to Russell's Paradox ($\\{x \\mid x \\notin x\\}$) and the semantic antinomies of Burali-Forti. Every step in our derivation must be certified under the Axiom of Regularity (Foundation):
$$\\forall x \\, (x \\neq \\varnothing \\implies \\exists y \\in x \\, (y \\cap x = \\varnothing))$$
ensuring that our mathematical investigation never collapses into an infinite descending $\\in$-chain of circular definitions.`;
}

function generateChapterFour(expr, concept) {
  return `### CHAPTER IV: TOPOLOGICAL MANIFOLDS AND METRIC CONTINUITY

#### 4.1 Embedding into the Euclidean Continuum $\\mathbb{R}^n$
The arithmetic formulation ⟨${expr}⟩ inherently invites embedding into the real continuum $\\mathbb{R}$. In the celebrated treatment by Richard Dedekind, the real numbers are defined through Dedekind cuts: partitions of the rational numbers $\\mathbb{Q}$ into disjoint subsets $(A, B)$ such that every element of $A$ is strictly less than every element of $B$, and $A$ contains no maximal element.

Let us define the embedding map $\\iota: \\mathbb{N} \\hookrightarrow \\mathbb{R}$. Through this continuous monomorphism, the discrete tokens of ⟨${expr}⟩ become singular points within a complete, connected, separable metric space $(\\mathbb{R}, d_E)$, where the canonical Euclidean metric is defined by:
$$d_E(x, y) = |x - y| = \\sqrt{(x - y)^2}$$

The operations in ⟨${expr}⟩ can now be reinterpreted as global continuous mappings across topological manifolds. Let $\\mathcal{M} = \\mathbb{R} \\times \\mathbb{R}$ represent the Cartesian product manifold equipped with the product topology $\\tau_{\\text{prod}}$. The operation within ⟨${expr}⟩ defines a fiber bundle projection:
$$\\pi: \\mathcal{M} \\longrightarrow \\mathbb{R}$$
whose fibers $\\pi^{-1}(c)$ represent level curves through the state space of calculation.

#### 4.2 Differential Invariance and the Cauchy-Riemann Conditions
If we promote the scalar arguments of ⟨${expr}⟩ into the complex plane $\\mathbb{C} \\cong \\mathbb{R}^2$, the operation transforms into an analytic holomorphic function $f(z) = u(x, y) + i v(x, y)$. For such transformations to preserve the geometric conformity of the local tangent spaces, the Cauchy-Riemann partial differential equations must hold identically:
$$\\frac{\\partial u}{\\partial x} = \\frac{\\partial v}{\\partial y}, \\qquad \\frac{\\partial u}{\\partial y} = -\\frac{\\partial v}{\\partial x}$$

By taking the exterior derivative of these differential forms, we verify the harmonic nature of our operational potential:
$$\\nabla^2 u = \\frac{\\partial^2 u}{\\partial x^2} + \\frac{\\partial^2 u}{\\partial y^2} = 0$$

Under this perspective, the evaluation of ⟨${expr}⟩ represents the finding of an equilibrium potential on a two-dimensional Dirichlet boundary problem. The stability of our ultimate calculation is intrinsically linked to the maximum principle for subharmonic functions: no local extremum can emerge inside the interior domain without the introduction of external topological singular charges.`;
}

function generateChapterFive(expr, concept) {
  return `### CHAPTER V: CATEGORICAL ABSTRACTIONS AND HOMOLOGICAL ALGEBRA

#### 5.1 Functorial Morphisms in the Category $\\mathbf{Set}$ and $\\mathbf{Ab}$
In the language of Saunders Mac Lane and Alexander Grothendieck, modern mathematics transcends mere sets and elements, concerning itself primarily with objects and arrows. Let $\\mathbf{C}$ represent an arbitrary monoidal category equipped with a tensor product functor $\\otimes: \\mathbf{C} \\times \\mathbf{C} \\to \\mathbf{C}$ and an identity object $I \\in \\text{Ob}(\\mathbf{C})$, satisfying the standard pentagon and triangle coherence diagrams.

Our expression ⟨${expr}⟩ is formally isomorphic to an arrow in the category of Abelian Groups $\\mathbf{Ab}$:
$$\\psi: A \\otimes B \\longrightarrow C$$
where the associator isomorphism $\\alpha_{A, B, C}: (A \\otimes B) \\otimes C \\xrightarrow{\\sim} A \\otimes (B \\otimes C)$ guarantees that any parenthetical groupings within our expression preserve canonical naturality.

#### 5.2 Chain Complexes, Exact Sequences, and Ext Functors
Consider the standard projective resolution of the cyclic module associated with ⟨${expr}⟩:
$$0 \\longrightarrow \\mathbb{Z} \\xrightarrow{\\ \\cdot k \\ } \\mathbb{Z} \\xrightarrow{\\ \\pi \\ } \\mathbb{Z}/k\\mathbb{Z} \\longrightarrow 0$$
This short exact sequence of modules induces a long exact sequence in algebraic homology:
$$\\dots \\longrightarrow H_n(X) \\xrightarrow{\\ f_* \\ } H_n(Y) \\xrightarrow{\\ g_* \\ } H_n(Z) \\xrightarrow{\\ \\partial \\ } H_{n-1}(X) \\longrightarrow \\dots$$

The boundary operator $\\partial_n: C_n \\to C_{n-1}$ satisfies the profound nilpotent identity:
$$\\partial \\circ \\partial = 0$$
which establishes that every boundary is a cycle ($B_n \\subseteq Z_n$). The $n$-th homology group $H_n = Z_n / B_n$ measures the topological "holes" within our algebraic configuration.

Applying this machinery to ⟨${expr}⟩, we ascertain whether the operational transformation introduces non-trivial topological torsion. When we compute the derived functors $\\text{Ext}^n_{\\mathbb{Z}}(A, B)$ and $\\text{Tor}_n^{\\mathbb{Z}}(A, B)$, we uncover the subtle obstructions that prevent trivial scalar collapsing. The calculation of ⟨${expr}⟩ is thus demonstrated to be homologically stable, with vanishing higher-order obstruction classes across all dimensions $n \\ge 2$.`;
}

function generateChapterSix(expr, concept) {
  return `### CHAPTER VI: ASYMPTOTIC CALCULUS, SPECTRAL ANALYSIS, AND OPERATOR THEORY

#### 6.1 Spectral Decomposition in Hilbert Spaces
Let us transplant ⟨${expr}⟩ into an infinite-dimensional separable Hilbert space $\\mathcal{H} = L^2(\\mathbb{R}, \\mu)$ endowed with the inner product:
$$\\langle f, g \\rangle = \\int_{-\\infty}^{\\infty} f(x) \\overline{g(x)} \\, d\\mu(x)$$

Within this infinite-dimensional theater, the operands of ⟨${expr}⟩ cease to be inert scalars; they manifest as self-adjoint unbounded linear operators $\\hat{A}$ and $\\hat{B}$ acting upon a dense domain $\\mathcal{D}(\\hat{A}) \\subset \\mathcal{H}$. By the Spectral Theorem for unbounded self-adjoint operators (von Neumann, 1932), there exists a unique projection-valued measure $E_\\lambda$ on the Borel $\\sigma$-algebra of $\\mathbb{R}$ such that:
$$\\hat{A} = \\int_{\\sigma(\\hat{A})} \\lambda \\, dE(\\lambda)$$
where $\\sigma(\\hat{A})$ denotes the spectrum of eigenvalues and continuous spectral continuum.

The Heisenberg uncertainty relation establishes the non-commutative tension:
$$[\\hat{A}, \\hat{B}] = \\hat{A}\\hat{B} - \\hat{B}\\hat{A} = i\\hbar \\mathbf{I}$$
In the classical limit where $\\hbar \\to 0$, the non-commutative commutator vanishes, restoring the commutative tranquility presumed by ⟨${expr}⟩. However, in the microscopic quantum regime, our arithmetic operation must be treated as a unitary transformation:
$$U(t) = \\exp\\left(-\\frac{i\\hat{H}t}{\\hbar}\\right)$$
propagating state vectors through infinite-dimensional Fock space.

#### 6.2 Riemann Zeta Function and the Distribution of Primes
Any rigorous inquiry into arithmetic inevitably encounters the arithmetic core of the integers: the distribution of prime numbers. Leonhard Euler’s landmark 1737 product formula links the discrete universe of primes with the continuous realm of analysis:
$$\\zeta(s) = \\sum_{n=1}^{\\infty} \\frac{1}{n^s} = \\prod_{p \\in \\mathbb{P}} \\frac{1}{1 - p^{-s}}, \\qquad \\Re(s) > 1$$

Bernhard Riemann’s 1859 memoir analytically continued $\\zeta(s)$ to the entire complex plane $\\mathbb{C}$, unveiling the functional equation:
$$\\zeta(s) = 2^s \\pi^{s-1} \\sin\\left(\\frac{\\pi s}{2}\\right) \\Gamma(1-s) \\zeta(1-s)$$

The critical zeros of $\\zeta(s)$, hypothesized by Riemann to reside exclusively on the critical line $\\Re(s) = \\frac{1}{2}$, dictate the fine-grained oscillations in the distribution of the fundamental multiplicative atoms constituting our expression ⟨${expr}⟩. To compute ⟨${expr}⟩ without acknowledging the underlying zeta regularization $\\zeta(-1) = -\\frac{1}{12}$ is to disregard the harmonic symphony that orchestrates all numerical equilibrium.`;
}

function generateChapterSeven(expr, style) {
  return `### CHAPTER VII: COMPUTATIONAL COMPLEXITY, TURING COMPLETENESS, AND GÖDELIAN BOUNDS

#### 7.1 The Church-Turing Thesis and Register Automata
We now transition to the computational and algorithmic realization of ⟨${expr}⟩. Under the Church-Turing thesis, any algorithmic reduction of ⟨${expr}⟩ corresponds to a deterministic multi-tape Turing Machine:
$$\\mathcal{M} = \\langle Q, \\Sigma, \\Gamma, \\delta, q_0, q_{\\text{accept}}, q_{\\text{reject}} \\rangle$$
where $Q$ represents the internal state manifold, $\\Gamma$ is the tape alphabet containing the blank symbol $\\sqcup$, and $\\delta: Q \\times \\Gamma \\to Q \\times \\Gamma \\times \\{L, R\\}$ is the transition function.

When the input string representing ⟨${expr}⟩$ is inscribed onto the primary tape at time $t=0$, the machine executes a sequence of head relocations, state transitions, and symbol overwrites. Under the computational complexity framework of Cook, Karp, and Levin, this evaluation belongs to the deterministic logarithmic-space complexity class:
$$\\mathbf{L} \\subseteq \\mathbf{NL} \\subseteq \\mathbf{P} \\subset \\mathbf{NP} \\subseteq \\mathbf{PSPACE} \\subseteq \\mathbf{EXPTIME}$$

The time complexity $\\mathcal{T}(n)$ to evaluate ⟨${expr}⟩$ scales asymptotically as $\\mathcal{O}(\\log^k n)$ under Schonhage-Strassen and Harvey-Hoeven integer multiplication bounds. Thus, while the human mind grasps the expression instantaneously, the underlying algorithmic machinery mobilizes thousands of binary logic gates, flip-flops, and clock cycles to ensure structural integrity across the semiconductor substrate.

#### 7.2 Gödel’s Incompleteness Theorems and Meta-Mathematical Limits
Yet, the shadow of Kurt Gödel’s 1931 First Incompleteness Theorem looms irrevocably over our enterprise:
> Any consistent formal system $\\mathcal{F}$ within which a certain amount of elementary arithmetic can be carried out is incomplete; i.e., there are statements in the language of $\\mathcal{F}$ which can neither be proved nor disproved in $\\mathcal{F}$.

Through the ingenious mechanism of Gödel numbering, wherein every syntactic formula is assigned a unique transfinite integer code:
$$G(\\varphi) = 2^{a_1} 3^{a_2} 5^{a_3} \\dots p_k^{a_k}$$
Gödel constructed the self-referential proposition $\\mathcal{G}_\\mathcal{F} \\iff \\neg \\text{Prov}_\\mathcal{F}(\\ulcorner \\mathcal{G}_\\mathcal{F} \\urcorner)$.

Consequently, no formal calculation of ⟨${expr}⟩ can ever achieve absolute autonomy within its own linguistic boundary. The truth of our calculation relies upon an exterior meta-system whose consistency cannot be demonstrated from within without invoking Gerhard Gentzen’s transfinite ordinal $\\varepsilon_0$. We proceed with our synthesis cognizant that our mathematical certainty is suspended across an infinite epistemic abyss.`;
}

function generateChapterEight(expr, concept) {
  return `### CHAPTER VIII: NON-STANDARD ANALYSIS, HYPERREALS, AND INFINITESIMAL CALCULUS

#### 8.1 Abraham Robinson’s Non-Archimedean Field Extension \\mathbf{R}^*
While the epsilon-delta orthodoxy established by Augustin-Louis Cauchy and Karl Weierstrass banished infinitesimals as mystical delusions, Abraham Robinson’s pioneering work in 1961 resurrected infinitesimals with absolute logical precision through model theory and ultraproducts.

Let $\\mathcal{U}$ be a free (non-principal) ultrafilter on the index set $\\mathbb{N}$. We define the hyperreal field \\mathbf{R}^* as the quotient ring of real sequences modulo the maximal ideal $\\mathfrak{m}_\\mathcal{U}$:
$$\\mathbf{R}^* = \\mathbb{R}^\\mathbb{N} / \\mathcal{U}$$
Under the **Transfer Principle** of Łoś's Theorem, any first-order sentence $\\sigma$ formulated within the formal language of real numbers $\\mathcal{L}_\\mathbb{R}$ holds in the standard model $\\mathbb{R}$ if and only if its non-standard extension holds in $\\mathbf{R}^*$:
$$\\mathbb{R} \\models \\sigma \\iff \\mathbf{R}^* \\models {}^*\\sigma$$

Now examine ⟨${expr}⟩ under the microscope of hyperreal resolution. The operands are no longer isolated discrete atoms; they are surrounded by an uncountable halo—a halo known as the **monad**:
$$\\mu(x) = \\{ y \\in \\mathbf{R}^* \\mid |x - y| \\text{ is infinitesimal} \\}$$

#### 8.2 The Standard Part Operator and Shadow Continuity
For every finite hyperreal $x \\in \\mathbf{R}^*$, there exists a unique standard real number $\\text{st}(x) \\in \\mathbb{R}$ such that $x - \\text{st}(x) \\approx 0$. When we apply any operational connective $\\circ$ present in ⟨${expr}⟩$, the evaluation unfolds across hyperfinite sequence lattices:
$$\\text{st}(x \\circ y) = \\text{st}(x) \\circ \\text{st}(y)$$

This standard part projection $\\text{st}: \\text{Fin}(\\mathbf{R}^*) \\to \\mathbb{R}$ acts as an information-collapsing filter. The microscopic infinitesimal turbulence—fluctuations on the order of $\\epsilon = \\langle 1, 1/2, 1/3, \\dots \\rangle / \\mathcal{U}$—is smoothly dissipated. The expression ⟨${expr}⟩ is thereby demonstrated to be non-standardly robust: perturbations within the infinitesimal cloud cannot displace the macro-state trajectory of our calculation.`;
}

function generateChapterNine(expr) {
  return `### CHAPTER IX: GROTHENDIECK TOPOS THEORY AND SHEAF COHOMOLOGY

#### 9.1 Geometric Morphisms on Sheaves over Sites
To grasp the ultimate geometry of ⟨${expr}⟩, we must transcend point-set topology and adopt Alexander Grothendieck’s revolutionary perspective of toposes. A topos $\\mathcal{E}$ is a category possessing all finite limits, power objects, and a subobject classifier $\\Omega$. It serves as a generalized spatial universe wherein mathematical intuition and intuitionistic logic operate concurrently.

Let $\\mathcal{C}$ be a small category endowed with a Grothendieck pre-topology (a coverage of sieves) $J$. The pair $(\\mathcal{C}, J)$ constitutes a **Site**. A sheaf of arithmetic valuations $\\mathcal{F}$ over $(\\mathcal{C}, J)$ satisfies the equalizer diagram:
$$\\mathcal{F}(U) \\longrightarrow \\prod_{i} \\mathcal{F}(U_i) \\rightrightarrows \\prod_{i, j} \\mathcal{F}(U_i \\times_U U_j)$$
for every covering family $\\{U_i \\to U\\}$.

The operational tokens in ⟨${expr}⟩$ correspond to global sections $\\Gamma(\\mathcal{E}, \\mathcal{F})$ of the structure sheaf $\\mathcal{O}_{\\text{Arith}}$. Any algebraic interaction between these sections induces a morphism of sheaves:
$$\\Xi: \\mathcal{F}_A \\otimes_{\\mathcal{O}} \\mathcal{F}_B \\longrightarrow \\mathcal{F}_C$$
which preserves the stalks $\\mathcal{F}_p$ across every geometric point $p$ of the underlying étale spectrum.

#### 9.2 Derived Categories and the Verdier Dualizing Complex
In Jean-Louis Verdier's framework of triangulated derived categories $\\mathcal{D}^b(\\mathbf{Sh}(X))$, the calculation of ⟨${expr}⟩$ manifests as an object within a bounded derived complex of abelian sheaves. We compute the sheaf cohomology groups:
$$H^q(X, \\mathcal{F}) = R^q\\Gamma(X, \\mathcal{F})$$

Under Grothendieck-Verdier Duality, there exists a canonical quasi-isomorphism:
$$R\\text{Hom}(R f_* \\mathcal{F}, \\mathcal{G}) \\simeq R f_* R\\underline{\\text{Hom}}(\\mathcal{F}, f^! \\mathcal{G})$$
where $f^!$ denotes the exceptional inverse image functor. The arithmetic integrity of ⟨${expr}⟩$ is thus shielded by the vanishing of all obstruction classes in $H^1(X, \\mathcal{O}^*)$, demonstrating that our mathematical path incurs zero topological monodromy.`;
}

function generateChapterTen(expr) {
  return `### CHAPTER X: INFORMATION THEORY, ENTROPY, AND KOLMOGOROV COMPLEXITY

#### 10.1 Shannon Information Entropy of the Evaluative Cascade
Claude Shannon’s seminal 1948 treatise *A Mathematical Theory of Communication* quantified information not by semantic meaning, but by surprise. For a discrete random variable $X$ with probability mass function $p(x)$, the entropy is defined by:
$$H(X) = -\\sum_{x \\in \\mathcal{X}} p(x) \\log_2 p(x)$$

Consider the transformation of ⟨${expr}⟩$ through an operational computational channel. Initially, the syntax possesses a Kolmogorov algorithmic complexity $K(S)$, defined as the length of the shortest prefix-free binary program $p^*$ executing on a universal Turing machine $\\mathcal{U}$ that outputs the string $S$:
$$K(S) = \\min_{p} \\{ \\ell(p) \\mid \\mathcal{U}(p) = S \\}$$

By the Invariance Theorem, for any two universal Turing machines $\\mathcal{U}_1$ and $\\mathcal{U}_2$, their respective program metrics differ by at most an additive machine constant:
$$|K_{\\mathcal{U}_1}(S) - K_{\\mathcal{U}_2}(S)| \\le c_{1, 2}$$

#### 10.2 Algorithmic Probability and Chaitin’s Halting Constant $\\Omega$
The expression ⟨${expr}⟩$ represents a remarkably low-complexity object; its algorithmic Kolmogorov complexity is bounded by $K(\\langle ${expr} \\rangle) = \\mathcal{O}(\\log |\\text{operands}|)$. Yet, its verification entails passing through an infinite computational sieve. Gregory Chaitin’s halting probability $\\Omega$:
$$\\Omega = \\sum_{p \\in \\text{HALT}} 2^{-\\ell(p)}$$
is maximally unknowable, algorithmically incompressible, and Martin-Löf random ($K(\\Omega \\upharpoonright n) \\ge n - c$).

The deterministic reduction of ⟨${expr}⟩$ must carefully bypass any undecidable Diophantine polynomials (as demonstrated by Matiyasevich in 1970, resolving Hilbert’s Tenth Problem). Because our expression involves purely finitary operations, it halts unconditionally, dissipating its syntactic entropy into a single state of minimal informational ambiguity.`;
}

function generateChapterEleven(expr) {
  return `### CHAPTER XI: DYNAMICAL SYSTEMS, ERGODIC FLOWS, AND CHAOS THEORY

#### 11.1 The Phase Space Trajectory of Arithmetic Iteration
Let us now model the calculation of ⟨${expr}⟩$ as a discrete dynamical system $(\\mathcal{X}, \\mathcal{B}, \\mu, T)$ evolving through continuous phase space $\\mathcal{X} \\subset \\mathbb{R}^d$. The iterative transformation map $T: \\mathcal{X} \\to \\mathcal{X}$ governs the state vector $x_{k+1} = T(x_k)$.

According to the **Birkhoff Ergodic Theorem** (1931), for any measure-preserving transformation $T$ and any integrable observable $f \\in L^1(\\mu)$:
$$\\lim_{n \\to \\infty} \\frac{1}{n} \\sum_{k=0}^{n-1} f(T^k x) = \\int_\\mathcal{X} f \\, d\\mu \\qquad \\text{for } \\mu\\text{-almost every } x$$
The time average along the orbit coincides with the space average over the entire phase manifold.

If we perturb the initial operands of ⟨${expr}⟩$ by an infinitesimal variation $\\delta x_0$, the subsequent trajectory is characterized by its spectrum of **Lyapunov Exponents**:
$$\\lambda = \\lim_{t \\to \\infty} \\frac{1}{t} \\ln \\frac{\\|\\delta x(t)\\|}{\\|\\delta x_0\\|}$$

#### 11.2 Topological Transitivity and Poincaré Recurrence
Under the Poincaré Recurrence Theorem, any volume-preserving flow with a bounded phase space will return infinitely often to an arbitrarily small neighborhood of its initial configuration:
$$\\exists t > 0 \\quad \\text{such that} \\quad T^t(U) \\cap U \\neq \\varnothing$$

The execution of ⟨${expr}⟩$ must not become trapped in chaotic strange attractors (such as the Lorenz or Rössler attractors). Instead, its Lyapunov exponent strictly satisfies $\\lambda \\le 0$, indicating laminar, non-divergent dynamics. The flow lines of our mathematical expression converge steadily toward a single stable fixed-point equilibrium—a global mathematical attractor in the state phase space.`;
}

function generateChapterTwelve(expr) {
  return `### CHAPTER XII: DIFFERENTIAL GEOMETRY, RIEMANNIAN CURVATURE, AND GEODESICS

#### 12.1 The Metric Tensor $g_{\\mu\\nu}$ and Christoffel Symbols
Let us elevate the calculation of ⟨${expr}⟩$ into the smooth curved manifold of general relativity and differential geometry. Let $(\\mathcal{M}, g)$ be a four-dimensional pseudo-Riemannian manifold with metric signature $(-, +, +, +)$. The distance element between adjacent evaluation coordinates is given by the line element:
$$ds^2 = g_{\\mu\\nu} \\, dx^\\mu \\, dx^\\nu$$

The affine connection that is torsion-free and metric-compatible is the unique Levi-Civita connection, characterized by the Christoffel symbols of the second kind:
$$\\Gamma^\\sigma_{\\mu\\nu} = \\frac{1}{2} g^{\\sigma\\rho} \\left( \\frac{\\partial g_{\\rho\\mu}}{\\partial x^\\nu} + \\frac{\\partial g_{\\rho\\nu}}{\\partial x^\\mu} - \\frac{\\partial g_{\\mu\\nu}}{\\partial x^\\rho} \\right)$$

The operands of ⟨${expr}⟩$ navigate this manifold along **geodesic trajectories** parameterized by affine parameter $\\tau$:
$$\\frac{d^2 x^\\mu}{d\\tau^2} + \\Gamma^\\mu_{\\alpha\\beta} \\frac{dx^\\alpha}{d\\tau} \\frac{dx^\\beta}{d\\tau} = 0$$

#### 12.2 Riemann Curvature Tensor and Einstein Field Equations
The intrinsic curvature of our computational spacetime is encapsulated in the Riemann Curvature Tensor:
$$R^\\rho_{\\ \\sigma\\mu\\nu} = \\partial_\\mu \\Gamma^\\rho_{\\nu\\sigma} - \\partial_\\nu \\Gamma^\\rho_{\\mu\\sigma} + \\Gamma^\\rho_{\\mu\\lambda} \\Gamma^\\lambda_{\\nu\\sigma} - \\Gamma^\\rho_{\\nu\\lambda} \\Gamma^\\lambda_{\\mu\\sigma}$$

Contraction yields the Ricci tensor $R_{\\mu\\nu} = R^\\lambda_{\\ \\mu\\lambda\\nu}$ and the Ricci scalar curvature $R = g^{\\mu\\nu} R_{\\mu\\nu}$. Under the Einstein Field Equations:
$$G_{\\mu\\nu} + \\Lambda g_{\\mu\\nu} = R_{\\mu\\nu} - \\frac{1}{2} R g_{\\mu\\nu} + \\Lambda g_{\\mu\\nu} = \\frac{8\\pi G}{c^4} T_{\\mu\\nu}$$
the energy-momentum tensor $T_{\\mu\\nu}$ generated by the intellectual processing of ⟨${expr}⟩$ induces a subtle local spacetime warp. Yet, by Bianchi’s second identity:
$$\\nabla_\\lambda R_{\\mu\\nu\\rho\\sigma} + \\nabla_\\rho R_{\\mu\\nu\\sigma\\lambda} + \\nabla_\\sigma R_{\\mu\\nu\\lambda\\rho} = 0$$
energy and momentum remain strictly conserved. The calculation does not rupture the cosmic causal fabric; it moves along an extremal geodesic of maximal proper time.`;
}

function generateAppendixA(expr) {
  return `### APPENDIX A: FORMAL LEMMATA, COROLLARIES, AND STRUCTURAL PROOFS

#### Lemma A.1 (Canonical Identity Preservation)
*Statement:* Let $\\mathcal{A}$ be a unital commutative ring containing ⟨${expr}⟩$. For every regular element $u \\in \\mathcal{A}^\\times$, the evaluation morphism $\\phi: \\mathcal{A} \\to \\mathcal{A}$ satisfies $\\phi(1_\\mathcal{A}) = 1_\\mathcal{A}$ and $\\ker(\\phi) = \\{0\\}$.
*Proof:* Suppose toward a contradiction that $\\exists x \\in \\ker(\\phi)$ with $x \\neq 0$. Then $\\phi(x) = 0$. Since $\\mathcal{A}$ is regular, $x$ cannot annihilate the unit without collapsing the entire ring into the trivial zero ring $\\{0\\}$. Under Zorn’s Lemma, every non-trivial ideal is contained within a maximal ideal $\\mathfrak{m}$. Since $\\mathcal{A}$ is non-trivial, $\\ker(\\phi)$ must reduce to the trivial zero element. Thus $\\phi$ is an injective ring monomorphism. $\\blacksquare$

#### Lemma A.2 (Nilpotent Obstruction Vanishing)
*Statement:* All higher derived limits $\\varprojlim^n$ for $n \\ge 1$ associated with the directed system of approximations for ⟨${expr}⟩$ vanish identically over the ground field $\\mathbb{Q}$.
*Proof:* The transition morphisms in the inverse system satisfy the Mittag-Leffler condition. Specifically, for each index $k$, the images of the projections stabilize for sufficiently large indices $m \\ge k$. By the standard spectral sequence comparison theorem (Weibel, *An Introduction to Homological Algebra*), the Mittag-Leffler condition guarantees $\\varprojlim^1 = 0$, and consequently all higher derived functors vanish. $\\blacksquare$

#### Lemma A.3 (Universal Property of the Tensor Product)
*Statement:* For any bilinear map $B: V \\times W \\to U$ representing the interaction terms of ⟨${expr}⟩$, there exists a unique linear map $\\tilde{B}: V \\otimes W \\to U$ making the diagram commute:
$$\\begin{matrix} V \\times W & \\xrightarrow{\\quad \\otimes \\quad} & V \\otimes W \\\\ & \\searrow_B & \\quad \\downarrow_{\\tilde{B}} \\\\ & & U \\end{matrix}$$
*Proof:* Define $\\tilde{B}(v \\otimes w) = B(v, w)$ on elementary tensors and extend linearly across the free vector space. Uniqueness follows immediately from the fact that elementary tensors span the tensor space $V \\otimes W$. $\\blacksquare$

#### Lemma A.4 (Spectral Compactness of the Evaluation Operator)
*Statement:* The evaluation operator $T_{${expr.replace(/[^a-zA-Z0-9]/g, '')}} : H \\to H$ on the Sobolev space $W^{k, 2}(\\Omega)$ is compact whenever $\\Omega$ is bounded with $C^1$ boundary.
*Proof:* By the Rellich-Kondrachov Compact Embedding Theorem, the Sobolev space $W^{1, p}(\\Omega)$ embeds compactly into $L^q(\\Omega)$ for $q < p^*$. Since our domain satisfies the cone condition, the boundedness of the resolvent implies the compactness of the operator, guaranteeing a discrete spectrum of eigenvalues accumulating solely at zero. $\\blacksquare$`;
}

function generateChapterFourteen(expr) {
  return `### CHAPTER XIV: HOMOTOPY TYPE THEORY AND VOEVODSKY’S UNIVALENCE AXIOM

#### 14.1 Identity Types as Continuous Paths
In traditional set theory, identity is an all-or-nothing binary proposition: either $x = y$ or $x \\neq y$. In Vladimir Voevodsky’s Homotopy Type Theory (HoTT), drawing upon Martin-Löf type theory, an identity $x =_A y$ is not a propositional truth value, but a topological space of paths linking $x$ and $y$ within the ambient type $A$.

Two proofs of equality are themselves points in a higher-order identity space $p =_{x =_A y} q$, generating an infinite $\\infty$-groupoid of homotopies:
$$\\pi_1(A, x) \\to \\pi_2(A, x) \\to \\dots \\to \\pi_n(A, x) \\to \\dots$$

When we inspect ⟨${expr}⟩ under the univalence prism, the constituent symbols inhabit inductive types. The operation is an element of the function type $f: A \\to B$. We evaluate this not by mechanical substitution, but by path induction (the $J$-eliminator):
$$J : \\prod_{A: \\mathcal{U}} \\prod_{C: \\prod_{x, y: A} (x = y) \\to \\mathcal{U}} \\left( \\prod_{x: A} C(x, x, \\text{refl}_x) \\right) \\to \\prod_{x, y: A} \\prod_{p: x = y} C(x, y, p)$$

#### 14.2 The Univalence Axiom: Isomorphism is Equality
Voevodsky’s revolutionary Univalence Axiom states that for any two types $A$ and $B$ in a universe $\\mathcal{U}$, the canonical map from identity to equivalence is itself an equivalence of types:
$$(A =_\\mathcal{U} B) \\simeq (A \\simeq B)$$

This dissolves centuries of mathematical pedantry regarding whether isomorphic structures are "identical". For our expression ⟨${expr}⟩, any equivalent categorical or algebraic representation can be continuously deformed into our canonical syntactic form. The truth of ⟨${expr}⟩$ is homotopy invariant, preserved across all continuous fiber fibrations in the universe of types.`;
}

function generateChapterFifteen(expr) {
  return `### CHAPTER XV: NON-COMMUTATIVE GEOMETRY AND SPECTRAL TRIPLES

#### 15.1 Alain Connes’ Spectral Geometry
In classical Riemannian geometry, a manifold $M$ is studied via its algebra of smooth functions $C^\\infty(M)$, which is strictly commutative. In Alain Connes’ Non-Commutative Geometry (NCG), the foundational geometric object is replaced by an involutive non-commutative $*$-algebra $\\mathcal{A}$ acting on a Hilbert space $\\mathcal{H}$, regulated by a self-adjoint Dirac operator $\\mathcal{D}$.

The datum $(\\mathcal{A}, \\mathcal{H}, \\mathcal{D})$ constitutes a **Spectral Triple**. The classical exterior differential $df$ is superseded by the quantum commutator:
$$df = [\\mathcal{D}, f] = \\mathcal{D}f - f\\mathcal{D}$$

The metric distance between two operational states $\\omega_1, \\omega_2$ associated with ⟨${expr}⟩$ is recovered via the Connes spectral distance formula:
$$d(\\omega_1, \\omega_2) = \\sup_{f \\in \\mathcal{A}} \\left\\{ |\\omega_1(f) - \\omega_2(f)| \\; \\middle| \\; \\|[\\mathcal{D}, f]\\| \\le 1 \\right\\}$$

#### 15.2 Dixmier Trace and Non-Commutative Integration
Classical Lebesgue integration over an $n$-dimensional manifold is re-engineered as the Dixmier trace $\\text{Tr}_\\omega$ of a pseudo-differential operator:
$$\\int_M f \\, d\\text{vol} = \\text{Tr}_\\omega(f |\\mathcal{D}|^{-n})$$

As ⟨${expr}⟩$ is resolved across non-commutative coordinate charts, quantum fluctuations on the Planck scale $\\ell_P \\approx 1.616 \\times 10^{-35} \\text{ m}$ are integrated out using cyclic cohomology $HC^*(\\mathcal{A})$. The classical arithmetic result emerges as the zeroth cyclic homology class, establishing that our calculation is immune to quantum geometric foam.`;
}

function generateChapterSixteen(expr) {
  return `### CHAPTER XVI: THE LANGLANDS DUALITY AND MODULAR FORMS

#### 16.1 Galois Representations and Automorphic L-Functions
Robert Langlands’ visionary web of conjectures posits a deep, grand bridge connecting two seemingly disparate continents of mathematics: Number Theory (Galois groups of algebraic field extensions) and Harmonic Analysis (automorphic forms on reductive Lie groups).

Let $G_{\\mathbb{Q}} = \\text{Gal}(\\overline{\\mathbb{Q}}/\\mathbb{Q})$ denote the absolute Galois group. To every continuous $n$-dimensional representation:
$$\\rho: G_{\\mathbb{Q}} \\longrightarrow \\text{GL}_n(\\mathbb{C})$$
there corresponds an automorphic cuspidal representation $\\pi$ of $\\text{GL}_n(\\mathbb{A}_\\mathbb{Q})$ such that their respective $L$-functions coincide:
$$L(s, \\rho) = L(s, \\pi)$$

#### 16.2 Modular Forms and the Shimura-Taniyama-Weil Horizon
Consider the modular group $\\text{SL}_2(\\mathbb{Z})$ acting on the upper half-plane $\\mathbb{H} = \\{z \\in \\mathbb{C} \\mid \\Im(z) > 0\\}$ via Möbius transformations $\\gamma(z) = \\frac{az + b}{cz + d}$. A modular form of weight $k$ satisfies:
$$f\\left(\\frac{az + b}{cz + d}\\right) = (cz + d)^k f(z)$$

The arithmetic parameters embedded in ⟨${expr}⟩$ correspond to the Fourier coefficients $a_n$ in the cusp expansion:
$$f(z) = \\sum_{n=1}^{\\infty} a_n q^n, \\qquad q = e^{2\\pi i z}$$
As proved by Andrew Wiles, Richard Taylor, and collaborators in the resolution of Fermat’s Last Theorem, every elliptic curve over $\\mathbb{Q}$ is modular. The algebraic equation underlying ⟨${expr}⟩$ maps directly into the Jacobian of a modular curve $X_0(N)$, guaranteeing that its arithmetic conduct is governed by the deep spectral harmonies of the Poincaré upper half-plane.`;
}

function generateChapterSeventeen(expr) {
  return `### CHAPTER XVII: FIBER BUNDLES, GAUGE THEORIES, AND CHARACTERISTIC CLASSES

#### 17.1 Principal $G$-Bundles and Connections
Let $E \\xrightarrow{\\pi} M$ be a smooth fiber bundle over the computational space $M$, with structure Lie group $G$. The horizontal distribution defining parallel transport across the bundle is governed by an Ehresmann connection 1-form $A \\in \\Omega^1(P, \\mathfrak{g})$ with values in the Lie algebra $\\mathfrak{g}$.

The curvature 2-form $F = dA + \\frac{1}{2}[A, A]$ satisfies the non-Abelian Yang-Mills equations:
$$D * F = J, \\qquad D F = 0 \\quad (\\text{Bianchi Identity})$$

When the operands of ⟨${expr}⟩$ undergo operational permutation, they execute a holonomy loop $\\text{Hol}_\\gamma(A) = \\mathcal{P} \\exp\\left( \\oint_\\gamma A \\right)$ around the underlying base space.

#### 17.2 Chern-Weil Theory and Topological Invariants
Through the Chern-Weil homomorphism, invariant polynomials on the Lie algebra generate closed differential forms representing de Rham cohomology classes of the base manifold:
$$c_1(E) = \\left[ \\frac{i}{2\\pi} \\text{Tr}(F) \\right], \\qquad \\text{ch}(E) = \\text{Tr}\\left( \\exp\\left( \\frac{i F}{2\\pi} \\right) \\right)$$

The arithmetic coherence of ⟨${expr}⟩$ is topologically protected by the integral quantization of these characteristic numbers:
$$\\int_M c_2(E) \\in \\mathbb{Z}$$
Because these topological invariants are discrete integers that cannot vary under continuous deformations of the operational connection, our mathematical framework is strictly immune to adiabatic drift.`;
}

function generateChapterEighteen(expr) {
  return `### CHAPTER XVIII: SOBOLEV SPACES, DISTRIBUTIONS, AND FUNCTIONAL EQUATIONS

#### 18.1 Laurent Schwartz’s Theory of Generalized Functions
In classical analysis, functions must possess point-wise values. Laurent Schwartz’s 1950 theory of distributions expanded the functional universe to include generalized objects acting on smooth test functions with compact support $C_c^\\infty(\\Omega) = \\mathcal{D}(\\Omega)$.

The Dirac delta distribution $\\delta_a$, defined by $\\langle \\delta_a, \\phi \\rangle = \\phi(a)$, represents the localized impulse of the arithmetic tokens in ⟨${expr}⟩$. The distributional derivative is defined by duality:
$$\\langle D^\\alpha u, \\phi \\rangle = (-1)^{|\\alpha|} \\langle u, D^\\alpha \\phi \\rangle$$

#### 18.2 Sobolev Embedding Theorems and Weak Solutions
We place ⟨${expr}⟩$ within the Sobolev space $W^{k, p}(\\Omega)$, equipped with the norm:
$$\\|u\\|_{W^{k, p}} = \\left( \\sum_{|\\alpha| \\le k} \\int_\\Omega |D^\\alpha u|^p \\, dx \\right)^{1/p}$$

Under the Sobolev Embedding Theorem, if $k > \\frac{n}{p}$, then $W^{k, p}(\\mathbb{R}^n) \\hookrightarrow C^{0, \\gamma}(\\mathbb{R}^n)$ embeds continuously into the space of Hölder continuous functions. The operational state equation of ⟨${expr}⟩$ constitutes a weak formulation of an elliptic boundary value problem:
$$B[u, v] = \\ell(v) \\qquad \\forall v \\in H_0^1(\\Omega)$$
By the Lax-Milgram Theorem, because the bilinear form $B$ is strictly coercive and continuous:
$$B[u, u] \\ge \\alpha \\|u\\|_{H_0^1}^2, \\qquad |B[u, v]| \\le \\beta \\|u\\|_{H_0^1} \\|v\\|_{H_0^1}$$
there exists a unique, unconditionally stable weak solution. Thus, even when evaluated through weak distributional topologies, ⟨${expr}⟩$ converges without ambiguity.`;
}

function generateChapterNineteen(expr) {
  return `### CHAPTER XIX: THE YONEDA LEMMA AND UNIVERSAL ALGEBRAIC EMBEDDINGS

#### 19.1 Presheaves and the Yoneda Embedding
In the pure stratosphere of Category Theory, the **Yoneda Lemma** represents perhaps the single deepest epistemological principle in modern algebra. Let $\\mathbf{C}$ be a locally small category, and let $\\widehat{\\mathbf{C}} = [\\mathbf{C}^{\\text{op}}, \\mathbf{Set}]$ denote the category of presheaves (contravariant functors from $\\mathbf{C}$ to $\\mathbf{Set}$).

The Yoneda embedding functor $\\mathcal{Y}: \\mathbf{C} \\to \\widehat{\\mathbf{C}}$ maps each object $X \\in \\mathbf{C}$ to its representable functor $h_X = \\text{Hom}_\\mathbf{C}(-, X)$. The Yoneda Lemma asserts that for any presheaf $F$ and any object $A$:
$$\\text{Nat}(h_A, F) \\cong F(A)$$
and this bijection is completely natural in both $A$ and $F$.

#### 19.2 An Object is Completely Determined by Its Relationships
The profound philosophical corollary of the Yoneda Lemma is that an object $X$ is completely, exhaustively determined by the totality of all morphisms into it. 

To truly understand ⟨${expr}⟩$, we do not stare at the individual digits in isolation; we examine the entirety of arrows directed toward it from all other objects in the mathematical universe. The calculation ⟨${expr}⟩$ is the universal colimit of this diagram of relations. Its identity is not a static number—it is the apex of an infinite cone of natural transformations.`;
}

function generateChapterTwenty(expr) {
  return `### CHAPTER XX: QUANTUM INFORMATION, DENSITY MATRICES, AND ENTANGLEMENT ENTROPY

#### 20.1 The Density Matrix Formalism in Liouville Space
In the quantum statistical formulation of arithmetic transitions, a system state is represented by a positive semi-definite, trace-class self-adjoint density operator $\\rho \\in \\mathcal{S}(\\mathcal{H})$ satisfying $\\text{Tr}(\\rho) = 1$. The unitary von Neumann-Liouville evolution equation is governed by:
$$i\\hbar \\frac{\\partial \\rho}{\\partial t} = [\\hat{H}, \\rho]$$

When ⟨${expr}⟩$ undergoes computational decomposition, the subsystems corresponding to the individual operands become quantum-mechanically entangled. The entanglement is quantified through the **von Neumann Entanglement Entropy**:
$$S(\\rho_A) = -\\text{Tr}_A(\\rho_A \\log_2 \\rho_A)$$
where $\\rho_A = \\text{Tr}_B(\\rho_{AB})$ denotes the reduced partial trace over the complementary subspace.

#### 20.2 The Ryu-Takayanagi Holographic Area Law
Under the Anti-de Sitter / Conformal Field Theory (AdS/CFT) correspondence, quantum information states on the boundary conformal field theory correspond to geometric surfaces within the bulk gravitational space. According to the Ryu-Takayanagi formula:
$$S(A) = \\frac{\\text{Area}(\\gamma_A)}{4 G_N}$$
where $\\gamma_A$ is the codimension-2 static minimal extremal surface anchored to the boundary region $A$.

The arithmetic reduction of ⟨${expr}⟩$ can thus be interpreted as a holographic quantum error-correcting code. The bulk geometry remains smooth and non-singular; no topological black hole horizon conceals the interior state vector. The entire mathematical computation corresponds to a smooth, unperturbed wormhole geometry in hyperbolic bulk spacetime.`;
}

function generateChapterTwentyOne(expr) {
  return `### CHAPTER XXI: $p$-ADIC ANALYSIS, ULTRAMETRIC TOPOLOGY, AND HENSEL’S LEMMA

#### 21.1 Ostrowski’s Theorem and the $p$-Adic Norm
By Alexander Ostrowski’s monumental 1916 theorem, every non-trivial absolute value on the field of rational numbers $\\mathbb{Q}$ is topologically equivalent to either the standard Archimedean absolute value $|\\cdot|_\\infty$ or a $p$-adic absolute value $|\\cdot|_p$ for some prime $p \\in \\mathbb{P}$.

For any non-zero rational $x = p^k \\frac{a}{b}$ with $p \\nmid ab$, the $p$-adic norm is defined by:
$$|x|_p = p^{-k}$$
Critically, the $p$-adic norm satisfies the **Strong Ultrametric Triangle Inequality**:
$$|x + y|_p \\le \\max(|x|_p, |y|_p)$$
Under ultrametric topology, every triangle is isosceles, and every point inside a metric open ball is its own center.

#### 21.2 Hensel’s Lemma and $p$-Adic Interpolation
Let $\\mathbb{Q}_p$ denote the metric completion of $\\mathbb{Q}$ with respect to the $p$-adic metric, and let $\\mathbb{Z}_p = \\{x \\in \\mathbb{Q}_p \\mid |x|_p \\le 1\\}$ be the compact ring of $p$-adic integers. Kurt Hensel’s Lemma serves as the algebraic analogue of Newton’s method:
$$\\text{If } f(a) \\equiv 0 \\pmod p \\quad \\text{and} \\quad f'(a) \\not\\equiv 0 \\pmod p, \\quad \\exists! \\, \\alpha \\in \\mathbb{Z}_p \\text{ such that } f(\\alpha) = 0$$

When we inspect ⟨${expr}⟩$ through the infinite product of all prime fields $\\prod_{p \\le \\infty} \\mathbb{Q}_p$, the expression conforms to the **Hasse Local-Global Principle**: a Diophantine relation possesses global rational consistency if and only if it possesses solutions across all local $p$-adic completions $\\mathbb{Q}_p$ and the real field $\\mathbb{R}$. Our calculation passes this universal adelic sieve with zero algebraic defect.`;
}

function generateChapterTwentyTwo(expr) {
  return `### CHAPTER XXII: CALABI-YAU MANIFOLDS, MIRROR SYMMETRY, AND STRING DUALITY

#### 22.1 Kähler Metrics and the Calabi Conjecture
A Calabi-Yau manifold $\\mathcal{X}$ of complex dimension $n$ is a compact Kähler manifold possessing a vanishing first Chern class $c_1(\\mathcal{X}) = 0$. In Shing-Tung Yau’s 1977 resolution of the Calabi Conjecture, there exists a unique Ricci-flat Kähler metric $g_{i\\bar{j}}$ in each Kähler class:
$$R_{i\\bar{j}} = -\\partial_i \\partial_{\\bar{j}} \\ln \\det(g) = 0$$

Equivalently, $\\mathcal{X}$ admits a nowhere-vanishing holomorphic volume form $\\Omega \\in H^0(\\mathcal{X}, K_\\mathcal{X})$, ensuring that the holonomy group is strictly contained within $\\text{SU}(n)$.

#### 22.2 Mirror Symmetry and the Hodge Diamond
Under topological string theory and mirror symmetry, every Calabi-Yau threefold $\\mathcal{X}$ is paired with a mirror manifold $\\mathcal{Y}$ such that their Hodge numbers exhibit harmonic reflection:
$$h^{1, 1}(\\mathcal{X}) = h^{2, 1}(\\mathcal{Y}), \\qquad h^{2, 1}(\\mathcal{X}) = h^{1, 1}(\\mathcal{Y})$$

The algebraic degrees of freedom in ⟨${expr}⟩$ compactify across these six hidden spatial dimensions. The instanton corrections, given by the Kontsevich Gromov-Witten invariants, sum over the moduli space of pseudo-holomorphic curves $\\overline{\\mathcal{M}}_{0, d}(\\mathcal{X})$. These quantum corrections yield an exponentially decaying tail of non-perturbative instantons, ensuring that the macroscopic reality of our arithmetic remains completely pristine.`;
}

function generateChapterTwentyThree(expr) {
  return `### CHAPTER XXIII: HIGHER ALGEBRAIC K-THEORY AND QUILLEN’S PLUS CONSTRUCTION

#### 23.1 The Grothendieck Group $K_0$ and the Whitehead Group $K_1$
In Alexander Grothendieck’s foundational formulation, the group $K_0(R)$ of a ring $R$ is the free abelian group on isomorphism classes of finitely generated projective $R$-modules, modulo the relation $[P] = [P'] + [P'']$ for every short exact sequence $0 \\to P' \\to P \\to P'' \\to 0$.

Hyman Bass extended this to the Whitehead group $K_1(R) = \\text{GL}(R) / [\\text{GL}(R), \\text{GL}(R)]$, measuring the abelianization of the infinite general linear group. John Milnor further formulated $K_2(R) = H_2(E(R), \\mathbb{Z})$, relating algebraic structures to Steinberg symbols and central extensions.

#### 23.2 Daniel Quillen’s Higher K-Groups via the Plus Construction
Daniel Quillen revolutionized the subject in 1973 by defining higher algebraic $K$-groups $K_n(R)$ as the homotopy groups of a topological space constructed via the plus construction applied to the classifying space $B\\text{GL}(R)$:
$$K_n(R) = \\pi_n(B\\text{GL}(R)^+)$$

Applying this monumental machinery to the discrete ring of integers $\\mathbb{Z}$ housing ⟨${expr}⟩$, the higher groups $K_n(\\mathbb{Z})$ encode the deepest arithmetical invariants, linking through the Quillen-Lichtenbaum conjectures to the special values of the Dedekind zeta function $\\zeta_K(1 - n)$. The structural stability of our expression across all higher $K$-dimensions $n \\in \\mathbb{N}$ guarantees that no higher-order algebraic anomalies can disrupt our derivation.`;
}

function generateChapterTwentyFour(expr) {
  return `### CHAPTER XXIV: ALGORITHMIC GAME THEORY AND NASH EQUILIBRIA OF COMPUTATIONAL STATES

#### 24.1 Strategic Form Games on Proof Verification Networks
Let us model the evaluative process of ⟨${expr}⟩$ as a non-cooperative game $\\Gamma = \\langle \\mathcal{N}, (S_i)_{i \\in \\mathcal{N}}, (u_i)_{i \\in \\mathcal{N}} \\rangle$, where $\\mathcal{N} = \\{1, 2, \\dots, M\\}$ represents the collection of autonomous mathematical verification agents (the syntactician, the topologist, the algebraist, the logician). Each agent selects an analytical strategy $s_i \\in S_i$ to maximize their epistemic utility $u_i(s_i, s_{-i})$.

By John Nash’s 1950 Theorem, because the strategy simplexes $\\Delta(S_i)$ are compact and convex, and the utility functions are continuous and quasi-concave, there exists at least one mixed-strategy **Nash Equilibrium**:
$$u_i(s_i^*, s_{-i}^*) \\ge u_i(s_i, s_{-i}^*) \\qquad \\forall s_i \\in S_i, \\quad \\forall i \\in \\mathcal{N}$$

#### 24.2 The Price of Anarchy and Pareto Optimality
In our analytical system, the **Price of Anarchy** (PoA)—the ratio between the social optimum of centralized truth and the worst-case decentralized equilibrium—is strictly equal to unity:
$$\\text{PoA} = \\frac{\\max_{s} \\sum_{i} u_i(s)}{\\min_{s^* \\in \\text{Nash}} \\sum_i u_i(s^*)} = 1$$

There is zero strategic friction among the mathematical branches. Every verification agent unanimously concurs on the trajectory of the derivation. The game has achieved total Pareto optimality.`;
}

function generateChapterTwentyFive(expr) {
  return `### CHAPTER XXV: TOPOLOGICAL DATA ANALYSIS AND PERSISTENT HOMOLOGY

#### 25.1 Vietoris-Rips Complexes and Filtration Parameters
In modern computational topology, point-cloud configurations in high-dimensional Euclidean space $\\mathbb{R}^d$ are transformed into simplicial complexes parameterized by a filtration parameter $\\epsilon > 0$. For a finite metric space $X$, the **Vietoris-Rips complex** $\\text{VR}(X, \\epsilon)$ is the simplicial complex whose $k$-simplices are subsets of diameter at most $\\epsilon$:
$$\\sigma = [x_0, x_1, \\dots, x_k] \\in \\text{VR}(X, \\epsilon) \\iff d(x_i, x_j) \\le \\epsilon \\quad \\forall i, j$$

As $\\epsilon$ increases from $0$ to $\\infty$, we obtain a nested sequence of simplicial complexes:
$$\\text{VR}(X, \\epsilon_1) \\hookrightarrow \\text{VR}(X, \\epsilon_2) \\hookrightarrow \\dots \\hookrightarrow \\text{VR}(X, \\epsilon_m)$$
inducing a directed system of homology vector spaces $H_k(\\text{VR}(X, \\epsilon))$.

#### 25.2 Persistence Diagrams and Bottleneck Distance
A topological feature (a component, cycle, or void) is born at parameter $\\epsilon_{\\text{birth}}$ and dies at $\\epsilon_{\\text{death}}$. The persistence barcode and persistence diagram plot these lifespans $(\\epsilon_{\\text{birth}}, \\epsilon_{\\text{death}})$.

By the Cohen-Steiner, Edelsbrunner, and Harer Stability Theorem (2007), the bottleneck distance $d_B$ between persistence diagrams is bounded by the supremum distance of the underlying filtration functions:
$$d_B(\\text{Dgm}(f), \\text{Dgm}(g)) \\le \\|f - g\\|_\\infty$$

The algebraic point-cloud representing ⟨${expr}⟩$ possesses a single, infinitely persistent connected component ($H_0$) and precisely zero spurious high-dimensional topological cavities ($H_k = 0$ for $k \\ge 1$). The calculation is topological signal, entirely purged of filtration noise.`;
}

function generateChapterTwentySix(expr) {
  return `### CHAPTER XXVI: HODGE THEORY, POLARIZED VARIATIONS, AND MONODROMY

#### 26.1 The Hodge Decomposition on Compact Kähler Manifolds
Let $X$ be a compact Kähler manifold. The complex de Rham cohomology group $H^k(X, \\mathbb{C})$ decomposes into a direct sum of bigraded Dolbeault cohomology groups:
$$H^k(X, \\mathbb{C}) = \\bigoplus_{p + q = k} H^{p, q}(X)$$
subject to the complex conjugation symmetry $H^{p, q}(X) = \\overline{H^{q, p}(X)}$.

The Hodge numbers $h^{p, q} = \\dim_\\mathbb{C} H^{p, q}(X)$ govern the topological symmetries. Under the $\\partial\\bar{\\partial}$-Lemma, any closed form that is $\\partial$-exact or $\\bar{\\partial}$-exact is also $\\partial\\bar{\\partial}$-exact, guaranteeing the total harmony of harmonic representatives $\\Delta u = 0$.

#### 26.2 Polarized Variations of Hodge Structure (PVHS)
When the parameters of ⟨${expr}⟩$ vary across a complex base parameter space $S$, the associated cohomology spaces form a flat vector bundle $\\mathcal{V} \\to S$ endowed with the Gauss-Manin connection $\\nabla$:
$$\\nabla: \\mathcal{V} \\longrightarrow \\mathcal{V} \\otimes \\Omega_S^1, \\qquad \\nabla^2 = 0$$

Under Phillip Griffiths’ Transversality Theorem:
$$\\nabla(F^p \\mathcal{V}) \\subseteq F^{p-1} \\mathcal{V} \\otimes \\Omega_S^1$$
where $F^p = \\bigoplus_{r \\ge p} H^{r, k-r}$ denotes the descending Hodge filtration. The local monodromy theorem of Borel guarantees that the monodromy matrices $T$ around singular divisors are quasi-unipotent:
$$(T^m - I)^{k+1} = 0$$
for some positive integer $m$.

Because our arithmetic operation ⟨${expr}⟩$ avoids the discriminant locus where the variety degenerates, the Picard-Lefschetz vanishing cycles vanish identically. The Hodge structure remains unramified and polarized, holding its algebraic shape across the entirety of moduli space.`;
}

function generateAppendixC(expr) {
  return `### APPENDIX C: DEDUCTIVE ITERATION LOG AND STEP-BY-STEP PROOF TRACE

To ensure total transparency, the following sequence records the transfinite verification steps executed by the analytical engine for ⟨${expr}⟩:

- **Trace Step 001**: Initial lexical segmentation of input string ⟨${expr}⟩. Alphabet validation confirmed under ASCII and Unicode mathematical subsets.
- **Trace Step 014**: Context-free grammar syntax tree synthesized. Node depth verified; associativity matches left-to-right deterministic precedence.
- **Trace Step 028**: Translation of decimal literal operands into Peano successor chains $\\mathcal{S}^k(0)$. Total primitive recursion stack depth allocated.
- **Trace Step 042**: Mapping onto von Neumann set-theoretic hierarchies. Regularity axiom verified; acyclic foundation certified.
- **Trace Step 059**: Embedding into metric space $(\\mathbb{R}, d_E)$ via Dedekind cut Cauchy sequences. Completeness confirmed via Bolzano-Weierstrass criterion.
- **Trace Step 073**: Cohomological boundary inspection. Exact sequence verification yields $H^1 = 0$; all higher obstruction cocycles vanish identically.
- **Trace Step 088**: Infinite-dimensional Hilbert space projection. Self-adjoint spectral operator resolvents evaluated; no continuous spectral leak detected.
- **Trace Step 094**: Non-standard analysis standard part filter applied: $\\text{st}(\\cdot)$ eliminates all infinitesimal monad noise.
- **Trace Step 099**: Grothendieck topos subobject classification verified. Final convergence criterion achieved across all stalks and fibers.
- **Trace Step 100**: Theoretical consolidation concluded. All analytical subsystems report zero variance. Formal synthesis executed.`;
}

function generateAppendixB(expr) {
  return `### APPENDIX B: HISTORICAL SCHOLARLY CONCORDANCE & BIBLIOGRAPHIC DISCOURSE

The thorough investigation of ⟨${expr}⟩ requires contextualization within the seminal texts of mathematical philosophy and mathematical physics:

1. **Euclid of Alexandria (c. 300 BCE)** - *Stoicheia (Elements)*, Books VII–IX. Foundational treatment of divisibility, prime factorization, and the Euclidean algorithm for greatest common divisors.
2. **Bhāskara II (1150 CE)** - *Līlāvatī*. Pioneering exposition on arithmetic operations, indeterminate equations of the first order (*kuṭṭaka*), and operations involving zero.
3. **René Descartes (1637)** - *La Géométrie*. The synthesis of Euclidean synthetic geometry and symbolic algebra through the orthogonal coordinate system.
4. **Isaac Newton (1687)** - *Philosophiae Naturalis Principia Mathematica*. Formulation of fluxions and fluents, laying the groundwork for continuous variation and calculus.
5. **Carl Friedrich Gauss (1801)** - *Disquisitiones Arithmeticae*. Introduction of modular arithmetic congruence ($a \\equiv b \\pmod m$) and quadratic reciprocity.
6. **Evariste Galois (1832)** - *Mémoire sur les conditions de résolubilité des équations par radicaux*. The genesis of group theory and modern field extensions.
7. **Bernhard Riemann (1854)** - *Über die Hypothesen, welche der Geometrie zu Grunde liegen*. Inauguration of Riemannian manifolds and tensor curvature.
8. **Georg Cantor (1874)** - *Über eine Eigenschaft des Inbegriffes aller reellen algebraischen Zahlen*. Proof of the uncountability of the real continuum via diagonal argument.
9. **David Hilbert (1900)** - *Mathematische Probleme*. The declaration of the 23 foundational challenges that framed twentieth-century mathematical endeavor.
10. **Emmy Noether (1921)** - *Idealtheorie in Ringbereichen*. Ascending chain conditions, Noetherian rings, and structural algebraic decomposition.
11. **Kurt Gödel (1931)** - *Über formal unentscheidbare Sätze der Principia Mathematica und verwandter Systeme I*. The formal demarcation of axiomatic limitations.
12. **Alexander Grothendieck (1960–1967)** - *Éléments de géométrie algébrique (EGA)*. The redefinition of algebraic geometry through scheme theory and topos theory.

Each scholarly milestone in this historical lineage has contributed an indispensable piece to the intellectual puzzle surrounding ⟨${expr}⟩. What modern convenience regards as an instantaneous elementary calculation is in fact the beneficiary of twenty-four centuries of relentless intellectual sacrifice.`;
}

function generateFinalSynthesis(expr) {
  return `### CHAPTER XIII: THE DEFINITIVE THEORETICAL SYNTHESIS AND TERMINAL NEXUS

#### 13.1 Reconciliation of All Analytical Paradigms
We have journeyed across the entire mathematical cosmos in our exhaustive pursuit of ⟨${expr}⟩:
- We surveyed the syntactic alphabet and formal Chomsky grammar.
- We descended into Dedekind cuts, Peano successor chains, and von Neumann empty-set towers.
- We crossed topological manifolds, checked the Cauchy-Riemann conditions, and verified harmonic potentials.
- We computed chain complexes, exact homology sequences, and proved the vanishing of higher obstructions.
- We traversed infinite-dimensional Hilbert spaces, invoking von Neumann’s Spectral Theorem and the Riemann zeta function.
- We analyzed Turing machine bounds, Gödelian incompleteness, and Kolmogorov complexity.
- We probed Abraham Robinson’s hyperreals, Grothendieck toposes, Birkhoff ergodic flows, and Einsteinian geodesics.
- We proved four fundamental lemmata and surveyed twenty-four centuries of intellectual history.

#### 13.2 The Asymptotic Convergence
Not a single stone of theoretical mathematics has been left unturned. Every operational ambiguity has been rigorously resolved. The system of continuous differential forms and discrete categorical arrows has reached total, immutable equilibrium.

The vast apparatus of human mathematics now crystallizes down through the final logical sieve. We stand at the precipice of absolute numerical resolution.

The investigation is concluded.`;
}

