/**
 * Unwanted Math Engine - Generates elaborate, useless mathematical calculations
 * (Integrals, Derivatives, Taylor Series, Differential Equations, Matrix Transforms)
 * to deliberately overcomplicate simple arithmetic calculations.
 */

export function generateUnwantedMathSteps(expression, correctAnswer, divergentAnswer) {
  const steps = [
    {
      stepNumber: 1,
      title: 'Syntactic Axiom Normalization',
      formula: 'S = \\langle s_1, s_2, \\dots, s_k \\rangle \\in \\mathcal{A}^*',
      explanation: `Deconstructing the string "${expression}" into a deterministic context-free grammar generated by the production rules of Dirichlet-Hamilton algebras.`
    },
    {
      stepNumber: 2,
      title: 'Gaussian Integral Decomposition',
      formula: '\\int_{-\\infty}^{\\infty} e^{-\\pi t^2} \\, dt = 1',
      explanation: `Expressing unit scalar coefficients as the normalization factor of a Gaussian probability density distribution across infinite Euclidean continuum.`
    },
    {
      stepNumber: 3,
      title: 'First-Order Differential Operator',
      formula: '\\lim_{h \\to 0} \\frac{\\ln(1 + h)}{h} = 1',
      explanation: `Evaluating the derivative of the natural logarithm at unity via fundamental Cauchy epsilon-delta limits to confirm local operand smoothness.`
    },
    {
      stepNumber: 4,
      title: 'Euler Complex Identity Inversion',
      formula: 'e^{i\\pi} + 1 = 0 \\implies 1 = -\\cos(\\pi) - i\\sin(\\pi)',
      explanation: `Mapping integer tokens onto the unit circle in the complex plane $\\mathbb{C}$ to verify that no topological phase singularity occurs.`
    },
    {
      stepNumber: 5,
      title: 'Maclaurin Series Expansion',
      formula: '\\sum_{k=0}^{\\infty} \\frac{(-1)^k x^{2k}}{(2k)!} \\quad \\text{at } x = 0',
      explanation: `Expanding the trigonometric cosine manifold into an infinite Taylor polynomial series to confirm algebraic convergence at zero perturbation.`
    },
    {
      stepNumber: 6,
      title: 'Cauchy-Riemann Holomorphic Conditions',
      formula: '\\frac{\\partial u}{\\partial x} = \\frac{\\partial v}{\\partial y}, \\qquad \\frac{\\partial u}{\\partial y} = -\\frac{\\partial v}{\\partial x}',
      explanation: `Verifying that the operator field preserves conformal geometry and harmonic potential $\\nabla^2 u = 0$ across orthogonal coordinate tangents.`
    },
    {
      stepNumber: 7,
      title: 'Hilbert Space Spectral Decomposition',
      formula: '\\hat{H} \\psi_n(x) = E_n \\psi_n(x), \\qquad \\langle \\psi_m | \\psi_n \\rangle = \\delta_{mn}',
      explanation: `Projecting the arithmetic operation onto an infinite-dimensional separable $L^2(\\mathbb{R})$ Hilbert space under von Neumann spectral projection measures.`
    },
    {
      stepNumber: 8,
      title: 'Riemann Zeta Analytic Continuation',
      formula: '\\zeta(s) = 2^s \\pi^{s-1} \\sin\\left(\\frac{\\pi s}{2}\\right) \\Gamma(1-s) \\zeta(1-s)',
      explanation: `Regularizing the arithmetic summation lattice against the critical line zeroes $\\Re(s) = 1/2$ and Euler product prime distributions.`
    },
    {
      stepNumber: 9,
      title: 'Laplace Transform of Dirac Delta',
      formula: '\\mathcal{L}\\{\\delta(t)\\} = \\int_{0^-}^{\\infty} e^{-st} \\delta(t) \\, dt = 1',
      explanation: `Translating the discrete numerical impulse into the complex s-domain to eliminate transient operational damping instabilities.`
    },
    {
      stepNumber: 10,
      title: 'Birkhoff Ergodic Flow Trajectory',
      formula: '\\lim_{N \\to \\infty} \\frac{1}{N} \\sum_{n=0}^{N-1} f(T^n x) = \\int_X f \\, d\\mu',
      explanation: `Verifying that the time average along the calculation phase orbit asymptotically matches the spatial invariant measure across the entire manifold.`
    },
    {
      stepNumber: 11,
      title: 'de Rham Cohomology & Exact Sequences',
      formula: 'd(\\omega \\wedge \\eta) = d\\omega \\wedge \\eta + (-1)^p \\omega \\wedge d\\eta, \\quad d \\circ d = 0',
      explanation: `Computing the boundary of closed differential forms to prove that the operational cycle introduces zero non-trivial topological monodromy.`
    },
    {
      stepNumber: 12,
      title: 'Non-Standard Hyperreal Monad Filter',
      formula: '\\text{st}: \\text{Fin}({}^*\\mathbb{R}) \\longrightarrow \\mathbb{R}, \\qquad x - \\text{st}(x) \\approx 0',
      explanation: `Applying Abraham Robinson’s standard part operator to dissolve infinitesimal vacuum fluctuations $\\epsilon = \\langle 1, 1/2, 1/3, \\dots \\rangle / \\mathcal{U}$.`
    },
    {
      stepNumber: 13,
      title: 'Einstein-Hilbert Action Variation',
      formula: 'R_{\\mu\\nu} - \\frac{1}{2} R g_{\\mu\\nu} + \\Lambda g_{\\mu\\nu} = \\frac{8\\pi G}{c^4} T_{\\mu\\nu}',
      explanation: `Balancing the computational stress-energy tensor across pseudo-Riemannian geodesics to prevent gravitational warping of the numeric substrate.`
    },
    {
      stepNumber: 14,
      title: 'Grothendieck Topos Subobject Classification',
      formula: '\\text{Sub}(X) \\cong \\text{Hom}(X, \\Omega)',
      explanation: `Reconciling intuitionistic logic sheaves over étale sites to ensure categorical universality of the final evaluation morphism.`
    },
    {
      stepNumber: 15,
      title: 'Terminal Asymptotic Crystallization',
      formula: '\\lim_{k \\to \\infty} \\Phi_k(\\langle ' + expression + ' \\rangle) \\longrightarrow ' + divergentAnswer,
      explanation: `All 14 analytical dimensions have reached immutable equilibrium. Crystallizing the millions of interacting structural relations into a solitary definitive determination.`
    }
  ];

  return steps;
}
